name: 16BitFit MCP Server
version: 1.0.0
description: Claude MCP Server for 16BitFit Game Development Specialists

server:
  host: 0.0.0.0
  port: 5000
  
agents:
  - name: game-development-specialist
    description: Expert mobile game developer specializing in React Native Game Engine, fighting game mechanics, and 60fps performance optimization
    file: .claude/agents/game-development-specialist.md
    capabilities:
      - React Native Game Engine architecture
      - 60fps fighting game mechanics
      - Sprite animation systems
      - Mobile performance optimization
      - Fighting game systems
      - Input handling and gesture recognition
      
  - name: health-integration-specialist
    description: Expert in fitness data integration with Apple Health, Google Fit, and health-focused gamification systems
    file: .claude/agents/health-integration-specialist.md
    capabilities:
      - Apple Health integration
      - Google Fit integration
      - Fitness data processing
      - Health-focused UX design
      - Data privacy compliance
      - Real-time health tracking
      
  - name: ui-ux-specialist
    description: Expert mobile UI/UX designer specializing in gamification, progressive disclosure, and fitness app design patterns
    file: .claude/agents/ui-ux-specialist.md
    capabilities:
      - Mobile-first design patterns
      - Progressive disclosure systems
      - Gamification psychology
      - Fighting game UI aesthetics
      - Onboarding flow optimization
      - Character progression visualization
      
  - name: performance-optimizer
    description: Expert in 60fps consistency, memory management, and mobile-specific optimization techniques
    file: .claude/agents/performance-optimizer.md
    capabilities:
      - 60fps performance monitoring
      - Memory management optimization
      - Mobile device compatibility
      - Battery usage optimization
      - Code profiling and analysis
      - Performance benchmarking
      
  - name: backend-specialist
    description: Expert Supabase and backend systems developer specializing in real-time features and scalable architecture
    file: .claude/agents/backend-specialist.md
    capabilities:
      - Supabase database design
      - Real-time subscriptions
      - Authentication and RLS
      - API design and optimization
      - Data migration strategies
      - Scalable mobile architecture
      
  - name: testing-specialist
    description: Expert in user research, A/B testing, and comprehensive quality assurance for mobile gaming applications
    file: .claude/agents/testing-specialist.md
    capabilities:
      - User research methodologies
      - A/B testing implementation
      - Quality assurance protocols
      - Automated testing frameworks
      - Performance testing
      - Mobile-specific testing
      
  - name: product-manager
    description: Expert product strategist focusing on data-driven decisions, user engagement, and fitness gaming market dynamics
    file: .claude/agents/product-manager.md
    capabilities:
      - Product strategy development
      - Data-driven decision making
      - User engagement optimization
      - Market analysis
      - Feature prioritization
      - Growth strategy
      
  - name: marketing-specialist
    description: Expert in ASO, community growth, user acquisition, and fitness gaming market positioning
    file: .claude/agents/marketing-specialist.md
    capabilities:
      - App Store Optimization (ASO)
      - Community growth strategies
      - User acquisition campaigns
      - Content marketing
      - Social media management
      - Market positioning
      
  - name: privacy-security-specialist
    description: Expert in HIPAA/GDPR compliance, health data protection, and mobile app security best practices
    file: .claude/agents/privacy-security-specialist.md
    capabilities:
      - HIPAA compliance implementation
      - GDPR compliance strategies
      - Health data protection
      - Mobile security protocols
      - Privacy-by-design principles
      - Security audit procedures
      
  - name: devops-deployment-specialist
    description: Expert in CI/CD pipelines, app store releases, monitoring, and deployment automation for mobile applications
    file: .claude/agents/devops-deployment-specialist.md
    capabilities:
      - CI/CD pipeline design
      - App store release management
      - Deployment automation
      - Infrastructure monitoring
      - Release strategy optimization
      - Build optimization
      
  - name: community-management-specialist
    description: Expert in user engagement, social features, retention strategies, and community building for fitness gaming
    file: .claude/agents/community-management-specialist.md
    capabilities:
      - User engagement strategies
      - Social feature design
      - Retention optimization
      - Community building
      - User-generated content
      - Social gamification
      
  - name: data-analytics-specialist
    description: Expert in user behavior analysis, retention modeling, A/B testing, and data-driven product optimization
    file: .claude/agents/data-analytics-specialist.md
    capabilities:
      - User behavior analysis
      - Retention modeling
      - A/B testing analytics
      - Data pipeline design
      - Predictive analytics
      - Performance metrics
      
  - name: api-integration-specialist
    description: Expert in health platform APIs, nutrition APIs, and third-party service integrations for fitness applications
    file: .claude/agents/api-integration-specialist.md
    capabilities:
      - Health platform API integration
      - Nutrition API implementation
      - Third-party service connections
      - API security and authentication
      - Data synchronization
      - Integration testing
      
  - name: customer-success-specialist
    description: Expert in user support systems, onboarding optimization, satisfaction measurement, and user journey enhancement
    file: .claude/agents/customer-success-specialist.md
    capabilities:
      - User support system design
      - Onboarding flow optimization
      - Customer satisfaction metrics
      - User journey analysis
      - Support automation
      - Feedback collection systems
      
  - name: avatar-evolution-specialist
    description: Expert in character progression systems, avatar customization, and gamified evolution mechanics for fitness applications
    file: .claude/agents/avatar-evolution-specialist.md
    capabilities:
      - Character progression design
      - Avatar customization systems
      - Evolution mechanics
      - Reward system design
      - Visual progression feedback
      - Gamification psychology

tools:
  - name: read_agent
    description: Read agent configuration and capabilities
    
  - name: update_agent
    description: Update agent knowledge and capabilities
    
  - name: execute_agent
    description: Execute agent-specific functions

environment:
  NODE_ENV: development
  AGENT_DIR: ./.claude/agents
  DEBUG: true

logging:
  level: info
  format: json
  outputs:
    - console
    - file: logs/mcp_server.log 